---
- name: bootstrap a basic bash shell environment
  hosts: localhost
  # become: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:

  - name: make directory structure
    file:
      path: "{{ item.path }}"
      state: "{{ item.state }}"
    with_items:
      - { path: '~/DEV', state: 'directory' }
      - { path: '~/DEV/TOOLS', state: 'directory' }
      - { path: '~/DEV/CAREER', state: 'directory' }
      - { path: '~/DEV/CAREER/MESHCANDY', state: 'directory' }
      - { path: '~/DEV/CAREER/SYMMETRYLABS', state: 'directory' }

  # role - get ahold of development dependencies for arm development
  # arm-none-eabi

  # - homebrew_tap:
  #     name: greymd/tools
  - homebrew:
      name: tmux-xpanes

  # - name: INSTALL UTILS
  #   apt:
  #     name: "{{ item.name }}"
  #     state: "{{ item.state }}"
  #   with_items:
  #     - { name: 'picocom', state: 'present' }
  
