---
# file: site.yml

# running this playbook configures every machine I have access to.
# I don't run site.yml often.

- include: workstation.yml
- include: headless.yml
- include: micro_nodes.yml # For use with RIOT nodes