---
- name: configure common functionality I expect in my RPi's
  hosts: raspberries
  remote_user: pi
  sudo: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:
sudo apt-get update
sudo apt-get install python-picamera python3-picamera
