- name: Get brew-cask and NEOVIM
  shell: "{{ item }}"
  with_items:
    - brew unlink brew-cask
    - brew install caskroom/cask/brew-cask
    - brew tap caskroom/versions
    - brew tap neovim/homebrew-neovim
    - brew install --HEAD neovim
  when: ansible_os_family == "Darwin"

- name: Link in tier 0 vimrc for spf13
  # shell: echo "source ~/environment/dotfiles/vimrc_1" > ~/.vimrc.local
  shell: echo "source ~/environment/dotfiles/vimrc" > ~/.vimrc.local