---
- include: debian.yml
  when: ansible_os_family == "Debian"

- include: darwin.yml
  when: ansible_os_family == "Darwin"

- name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
  shell: curl http://j.mp/spf13-vim3 -L -o - | sh     creates=~/.spf13-vim-3



# Set up user

- name: configuring git for Nate Argetsinger - narget@umich.edu
  shell: "{{item}}"
  with_items:
  - git config --global user.name "Nate Argetsinger"
  - git config --global user.email narget@umich.edu
  - git config --global push.default simple

- name: make the directories I'll get_url into
  file: state=directory path={{ item }}
  with_items:
    - '~/config/util'
    - '~/dev'




- name: Determining username
  action: shell whoami
  register: whoami
  sudo: false


- name: Changing the default shell to zsh FOR ROOT
  sudo: true
  shell: chsh -s /bin/zsh

- pause: chsh requires login to take effect


- name: Backing up existing ~/.zshrc but only if ~/.oh-my-zsh isn't already present
  action: shell if [ ! -d ~/.oh-my-zsh ]; then if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi fi


- name: Installing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)
  action: git repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh update=no

- name: clone the repo
  git: repo=git@github.com:nargetdev/dotfiles.git dest=~/config/dotfiles clone=yes accept_hostkey=true

- name: set up oh-my-zsh via script
  shell: wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh

- name: default oh my zsh
  shell: cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc    creates=~/.zshrc

- name: set up shell
  shell: echo "source ~/config/dotfiles/zshrc" >> ~/.zshrc




##########################################################################################
###############           Flavor               ###########################################
##########################################################################################

- name: get some urls solarized
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
  - { url: 'http://ethanschoonover.com/solarized/files/solarized.zip', dest: '~/config/colors'}
  # - { url: 'http://www.apptivateapp.com/resources/Apptivate.app.zip', dest: '~/config/util'}

- name: git fonts for powerline
  action: git dest=~/config/powerline_fonts repo=https://github.com/powerline/fonts.git update=no

- name: In
  apt: name={{ item }} state=present
  sudo: true
  with_items:
    - wget
    - leiningen
    - htop
  when: ansible_os_family == "Debian"
