---

- name: make the directories I'll get_url into
  file: state=directory path=~/config/util

- name: Make sure required home directories exist
  file: name={{ item }} state=directory
  with_items:
      - '{{ home }}/dev'
      - '{{ home }}/config'

- name: clone the repo
  git: repo=git@github.com:nargetdev/dotfiles.git dest=~/config/dotfiles clone=yes accept_hostkey=true

- name: Install required software
  homebrew: name={{ item }} state=present
  with_items:
    - ack
    - git
    - vim
    - zsh
    - wget
    - macvim
    - bats
    - leiningen
    - processing
    - zsh
    # - vim-enhanced
    - git
    - tmux
    - htop
    - binutils
  when: ansible_os_family == "Darwin"

- name: Install ancillary applications
  homebrew_cask: name={{ item }} state=present
  with_items:
      - firefox
      - google-chrome
      - pycharm
      - atom
      - sublime-text3
      - adobe-creative-cloud
      - iterm2
      - codekit
      - spotify
  when: ansible_os_family == "Darwin"

- name: Install required software
  apt-get: name={{ item }} state=present
  with_items:
    - ack
    - git
    - vim
    - zsh
    - wget
    - bats
    - leiningen
    - processing
    - zsh
    - git
    - tmux
    - htop
  when: ansible_os_family == "Debian"


- name: Get brew-cask and NEOVIM
  shell: "{{ item }}"
  with_items:
    - brew install caskroom/cask/brew-cask
    - brew tap caskroom/versions
    - brew tap neovim/homebrew-neovim
    - brew install --HEAD neovim
  when: ansible_os_family == "Darwin"


- name: configuring git for Nate Argetsinger - narget@umich.edu
  shell: "{{item}}"
  with_items:
  - git config --global user.name "Nate Argetsinger"
  - git config --global user.email narget@umich.edu




- name: Determining username
  action: shell whoami
  register: whoami
  sudo: False


- name: Changing the default shell to zsh
  shell: chsh -s /bin/zsh



- name: Backing up existing ~/.zshrc but only if ~/.oh-my-zsh isn't already present
  action: shell if [ ! -d ~/.oh-my-zsh ]; then if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi fi


- name: Installing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)
  action: git repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh update=no


- name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
#   action: shell if [ ! -d ~/.spf13-vim-3 ]; then $(curl http://j.mp/spf13-vim3 -L -o - | sh); fi
  shell: curl http://j.mp/spf13-vim3 -L -o - | sh creates=~/.spf13-vim-3



- name: get my repos
  git: repo=git@github.com:nargetdev/website_V3.git dest=~/ddev/web/mysite clone=yes accept_hostkey=true


- name: grab xcode
  git: repo={{ item.repo }} dest={{ item.dest }} clone={{ item.clone }} accept_hostkey={{ item.accept_hostkey }}
  with_items:
  - { repo: 'git@github.com:XVimProject/XVim.git', dest: '~/config/xcode_mod/XVim', clone: 'yes', accept_hostkey: 'true'}



##########################################################################################
###############     Authentication for Git     ###########################################
##########################################################################################

- name: create ssh key
  command: ssh-keygen -t rsa -C "narget@umich.edu" -f ~/.ssh/id_rsa

- name: pipe key to clipboard
  shell: cat ~/.ssh/id_rsa.pub | pbcopy

- name: wait to put on github
  pause: prompt="please go put the pub key in your clipboard on github"


# Set up user

- name: configuring git for Nate Argetsinger - narget@umich.edu
  shell: "{{item}}"
  with_items:
  - git config --global user.name "Nate Argetsinger"
  - git config --global user.email narget@umich.edu


##########################################################################################
###############           Flavor               ###########################################
##########################################################################################

- name: get some urls solarized
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
  - { url: 'http://ethanschoonover.com/solarized/files/solarized.zip', dest: '~/config/colors'}
  # - { url: 'http://www.apptivateapp.com/resources/Apptivate.app.zip', dest: '~/config/util'}

- name: git fonts for powerline
  action: git dest=~/config/powerline_fonts repo=https://github.com/powerline/fonts.git update=no

