---
  ###
  ###
  ###
  # This file is to bootstrap a meshcandy workstation
  ###
  ###
  ###
- name: make directory structure
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items:
    - { path: '{{ ansible_env.HOME }}/DEV', state: 'directory' }
    - { path: '{{ ansible_env.HOME }}/DEV/INFRASTRUCTURE_AUTOMATION', state: 'directory' }

# create aliases for places I need to go
