- debug: msg="hello you've reached debian"

################################################################################
#####     Authentication for Git     ###########################################
################################################################################

# - name: create ssh key
#   command: ssh-keygen -t rsa -C "narget@umich.edu" -f ~/.ssh/id_rsa     creates=~/.ssh/id_rsa
#   register: key_result

  
# # install a text editor

# # You're gonna need this to get into github

- name: Generate SSH keys with no password and without user intervention
  shell: ssh-keygen -b 2048 -t rsa -f '{{ansible_env.HOME}}'/.ssh/id_rsa -q -N ""
  args:
    creates: '{{ansible_env.HOME}}/.ssh/id_rsa'
  register: key_result



# - name: use the ssh key
#   lineinfile: dest={{ item.file }} state=present line={{ item.line }}
#   with_items:
#     - { line: 'eval "$(ssh-agent -s)"', file: "{{lookup('env', 'HOME')}}/.bashrc" }
#     - { line: 'eval "$(ssh-agent -s)"', file: "{{lookup('env', 'HOME')}}/.zshrc" }
#     - { line: 'ssh-add ~/.ssh/id_rsa', file: "{{lookup('env', 'HOME')}}/.bashrc" }
#     - { line: 'ssh-add ~/.ssh/id_rsa', file: "{{lookup('env', 'HOME')}}/.zshrc" }
    
    
# - name: pipe key to clipboard UBUNTU
#   shell: cat ~/.ssh/id_rsa.pub | xclip -selection c

- name: display key
  debug:
    msg:
      - "the value of key is:"
      - "{{lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: wait to put on github
  pause: prompt="please go put ^^that pub key in your clipboard on github"
  when: key_result.changed

- debug: msg="prompt skipped"
  when:  key_result is succeeded

- name: configuring git for Nate Argetsinger - narget@umich.edu
  shell: "{{item}}"
  with_items:
  - git config --global user.name "Nate Argetsinger"
  - git config --global user.email narget@umich.edu
  - git config --global push.default simple