---
- name: make directory structure
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items:
    - { path: '{{HOME_PATH}}/DEV', state: 'directory' }
    - { path: '{{HOME_PATH}}/DEV/TOOLS', state: 'directory' }

# role - get ahold of development dependencies for arm development
## arm-none-eabi
- name: Download arm-none-eabi
  get_url:
    url: 'https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2?revision=2cc92fb5-3e0e-402d-9197-bdfc8224d8a5?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,6-2017-q2-update'
    dest: '{{HOME_PATH}}/DEV/TOOLS/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2'

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src:  '{{HOME_PATH}}/DEV/TOOLS/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2'
    dest: '{{HOME_PATH}}/DEV/TOOLS'
    remote_src: yes

# - name: add stuff to the PATH


##################################

# - name: INSTALL UTILS - tmux
#   apt:
#     name: "{{ item.name }}"
#     state: "{{ item.state }}"
#   with_items:
#     - { name: 'tmux', state: 'present' }
