---
- name: Are we initializing the whole system?
  when: sys_init
  include: sys_init.yml

# - name: add several users
#   user: name={{ item.name }} state=present groups={{ item.groups }}
#   with_items:
#     - { name: 'testuser1', groups: 'wheel' }
#     - { name: 'testuser2', groups: 'root' }

- name: make the directories I'll get_url into
  file: state=directory path=~/config/util

- name: get some urls solarized
  get_url: url={{ item.url }} dest={{ item.dest }}
  with_items:
  - { url: 'http://ethanschoonover.com/solarized/files/solarized.zip', dest: '~/config/colors'}
  # - { url: 'http://www.apptivateapp.com/resources/Apptivate.app.zip', dest: '~/config/util'}

- name: git fonts for powerline
  action: git dest=~/config/powerline_fonts repo=https://github.com/powerline/fonts.git update=no

- name: sanity
  debug: msg="is it osx?"

- name: are we osx?
  include: osx.yml
  when: osx
