---
- name: Are we initializing the whole system?
  when: sys_init
  include: sys_init.yml



- name: get solarized
  get_url: url=http://ethanschoonover.com/solarized/files/solarized.zip dest=~/config/colors

- name: sanity
  debug: msg="is it osx?"

- name: are we osx?
  include: osx.yml
  when: osx
