---
- name: Make sure required system directories exist
  file: name={{ item }} state=directory owner={{ ansible_user_id }}
  sudo: yes
  with_items:
  - /opt/rubies

- name: Make sure required home directories exist
  file: name={{ item }} state=directory
  with_items:
      - '{{ home }}/code'

# - include: redis.yml
# - include: mysql.yml
# - include: ruby.yml

- name: ensure cask is ready
  shell: brew tap caskroom/cask

- name: Install ancillary applications
  homebrew_cask: name={{ item }} state=present
  with_items:
      - alfred
      - firefox
      - google-chrome
      - virtualbox
      - textmate
      - pycharm
      - sublime-text
      - iterm2
      - codekit

- name: activate codekit
  pause: prompt="gvZobKg72x+rla7wxPalmW+pXQe8bVDqNuRP7oR0KYKjfXyELnPN5CVav0cM2P5YdVnlBB3jChzZeaQDULiAxOLM6Z1SbQTDQo3d3mlaGbIqWdqynDySxSROiSq5SgJlOth0TQAA5yE6hMsReYEbgkKiK9zNcfZc73RyPA8913CCCsUTrxG8e89s+0LqTBC5btLFCpuvgse5n0HgrBHV4VuCBlIbfDtezAeoapFSyFCnZ2vxrsiOTmip8ZkqlfUZa9KEj/+Ix3WjxJgIYCH8DTZ1jyI82H5xVuTIrV27V39uC96KpA3jSrg3IlYytqubGxNref7xy+g8ufBRrfmkKHoMIYZvc1GjrhLC37Qn3ZvlM2/jqjwP1QSl1pyA0XTHDTti4tnUux4SjQe5tclUDtlPL9PZ9jK6wkfsR0lgtCS3GGGtVsUs35GXQjB2BoixXivHEKBdlG9KbBDZzUNkwdYUHz3nR9zfFGBv7qt48UzcCy3Dduql0lm2m0C1mzgtl/o8Rn16qNBzVtUxdEeQgQy2Xy8apQTy5kc+z4YBt2KWaUVorW+aPImNOMz2h+k9xMiMVHSwFCwLLZq0kC67EmHFAbEkmvzJIKKpqz5/pYLcML6vS2c4Rz9W2E8GlgDMA8r/zpAIKedJQF4/oEtDuZVCzmFkEXMXycJi/RLbuHE="

- name: put sublime in it's place
  shell: sudo ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /bin/subl  creates=/bin/subl

# - name: go get JRE for pycharm
#   get_url: force=no url=https://support.apple.com/downloads/DL1572/en_US/JavaForOSX2014-001.dmg dest=~/config

- name: Install required software
  homebrew: name={{ item }} state=present
  with_items:
    - ack
    - git
    - vim
    - bats
    - leiningen
    - zsh

- name: Change sh to zsh
  sudo: yes
  shell: chsh -s /bin/zsh

- name: get dat oh-my-zsh
  sudo: yes
  shell:  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh


# - include: emacs.yml

# - include: pow.yml
