---
- name: Make sure required system directories exist
  file: name={{ item }} state=directory owner={{ ansible_user_id }}
  sudo: yes
  with_items:
  - /opt/rubies

- name: Make sure required home directories exist
  file: name={{ item }} state=directory
  with_items:
      - '{{ home }}/code'

# - include: redis.yml
# - include: mysql.yml
# - include: ruby.yml

- name: ensure cask is ready
  shell: brew tap caskroom/cask

- name: Install ancillary applications
  homebrew_cask: name={{ item }} state=present
  with_items:
      - alfred
      - firefox
      - google-chrome
      - virtualbox
      - textmate
      - pycharm
      - sublime-text
      - iterm2
      - codekit

- name: activate codekit
  pause: prompt="gvZobKg72x+rla7wxPalmW+pXQe8bVDqNuRP7oR0KYKjfXyELnPN5CVav0cM2P5YdVnlBB3jChzZeaQDULiAxOLM6Z1SbQTDQo3d3mlaGbIqWdqynDySxSROiSq5SgJlOth0TQAA5yE6hMsReYEbgkKiK9zNcfZc73RyPA8913CCCsUTrxG8e89s+0LqTBC5btLFCpuvgse5n0HgrBHV4VuCBlIbfDtezAeoapFSyFCnZ2vxrsiOTmip8ZkqlfUZa9KEj/+Ix3WjxJgIYCH8DTZ1jyI82H5xVuTIrV27V39uC96KpA3jSrg3IlYytqubGxNref7xy+g8ufBRrfmkKHoMIYZvc1GjrhLC37Qn3ZvlM2/jqjwP1QSl1pyA0XTHDTti4tnUux4SjQe5tclUDtlPL9PZ9jK6wkfsR0lgtCS3GGGtVsUs35GXQjB2BoixXivHEKBdlG9KbBDZzUNkwdYUHz3nR9zfFGBv7qt48UzcCy3Dduql0lm2m0C1mzgtl/o8Rn16qNBzVtUxdEeQgQy2Xy8apQTy5kc+z4YBt2KWaUVorW+aPImNOMz2h+k9xMiMVHSwFCwLLZq0kC67EmHFAbEkmvzJIKKpqz5/pYLcML6vS2c4Rz9W2E8GlgDMA8r/zpAIKedJQF4/oEtDuZVCzmFkEXMXycJi/RLbuHE="

- name: put sublime in it's place
  shell: sudo ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /bin/subl  creates=/bin/subl

########################################################################
# I'd like to be able to automate my sublime build:
# Steps Necessary:
# 1) install package manager:
#   import urllib2,os,hashlib; h = 'eb2297e1a458f27d836c04bb0cbaf282' + 'd0e7a3098092775ccb37ca9d6b2e4b7d'; pf = 'Package Control.sublime-package'; ipp = sublime.installed_packages_path(); os.makedirs( ipp ) if not os.path.exists(ipp) else None; urllib2.install_opener( urllib2.build_opener( urllib2.ProxyHandler()) ); by = urllib2.urlopen( 'http://packagecontrol.io/' + pf.replace(' ', '%20')).read(); dh = hashlib.sha256(by).hexdigest(); open( os.path.join( ipp, pf), 'wb' ).write(by) if dh == h else None; print('Error validating download (got %s instead of %s), please try manual install' % (dh, h) if dh != h else 'Please restart Sublime Text to finish installation')
# 2) Install packages I use:
#   a) Emmet
#   b) HTML-CSS-JS-Prettify
########################################################################

# - name: go get JRE for pycharm
#   get_url: force=no url=https://support.apple.com/downloads/DL1572/en_US/JavaForOSX2014-001.dmg dest=~/config

- name: Install required software
  homebrew: name={{ item }} state=present
  with_items:
    - ack
    - git
    - vim
    - bats
    - leiningen
    - zsh
    - node

- name: Change sh to zsh
  sudo: yes
  shell: chsh -s /bin/zsh

- name: get dat oh-my-zsh
  sudo: yes
  shell:  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh


# - include: emacs.yml

# - include: pow.yml
